name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Build
      run: |
        # Comandos para construir o projeto
        npm install
        npm run build

    - name: Criação do Artefato
      run: |
        # Comandos para criar o artefato
        mkdir dist
        cp -r * dist/
      artifacts:
        path: dist

  security_analysis:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Análise SAST
      # Substitua 'security-scanner' pelo seu scanner SAST
      run: security-scanner

    - name: Análise DAST
      # Substitua 'dast-scanner' pelo seu scanner DAST
      run: dast-scanner

    - name: Evidência do Repositório com SCA e Proteção de Credenciais
      # Substitua 'sca-scanner' e 'credential-scanner' pelas ferramentas de SCA e Proteção de Credenciais
      run: |
        sca-scanner
        credential-scanner

  deploy:
    runs-on: ubuntu-latest

    needs: security_analysis

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Deploy no Servidor de Aplicação
      # Substitua 'deploy-script.sh' pelo seu script de deploy
      run: ./deploy-script.sh

    - name: Evidência da Aplicação em Execução no Servidor
      run: ps aux
