name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Inicializar Terraform
      run: terraform init

    - name: Validar Configuração Terraform
      run: terraform validate

    - name: Aplicar Infraestrutura
      run: terraform apply -auto-approve
