name: Meu Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifacts: ${{ steps.package.outputs.artifacts }}

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Ambiente
      run: |
        npm install
        npm run build

    - name: Testar
      run: npm test

    - name: Empacotar Artefato
      id: package
      run: |
        mkdir dist
        cp -r * dist/

      # Defina os artefatos para serem utilizados em outros jobs ou na ação principal
      outputs:
        artifacts: dist
